import {test,expect,vi,beforeEach} from 'vitest';
const state=vi.hoisted(()=>({owner:'owner-a',session:null as null|{ownerId:string},reads:0}));
vi.mock('@/lib/server/auth',()=>({getRequestAuth:async()=>({user:state.owner?{id:state.owner}:null})}));
vi.mock('@/lib/server/appSession',()=>({getAppSessionFromRequest:()=>state.session}));
vi.mock('@/lib/server/supabase',()=>({getSupabaseAdmin:()=>({from:()=>{state.reads++;throw new Error('NO_UNEXPECTED_DATABASE_READ');}})}));
import {GET} from '@/app/api/health/route';
beforeEach(()=>{state.owner='owner-a';state.session=null;state.reads=0;});
const get=(query='petId=test-pet')=>GET(new Request(`http://localhost/api/health?${query}`));
test('anonymous and conflicting identities never read records',async()=>{state.owner='';expect((await get()).status).toBe(401);state.owner='owner-a';state.session={ownerId:'owner-b'};expect((await get()).status).toBe(403);expect(state.reads).toBe(0);});
test('invalid continuation fails closed before a query',async()=>{expect((await get('petId=test-pet&before=not-json')).status).toBe(400);expect(state.reads).toBe(0);});
