import { it, expect, vi, beforeEach } from 'vitest';
const mocks = vi.hoisted(() => ({ auth: vi.fn(), session: vi.fn(), db: vi.fn() }));
vi.mock('@/lib/server/auth', () => ({ getRequestAuth: mocks.auth }));
vi.mock('@/lib/server/appSession', () => ({ getAppSessionFromRequest: mocks.session }));
vi.mock('@/lib/server/supabase', () => ({ getSupabaseAdmin: mocks.db, demoModeResponse: () => ({}) }));
import { POST } from '../../../app/api/map/features/route';
import { PATCH } from '../../../app/api/map/features/[id]/route';
import { normalizeOwnerRoutes } from '../../../lib/mapUi';
const plan = { version: 1, mode: 'walking', stops: [{ point: [37, 55], title: 'Начало' }, { point: [37.002, 55.002], title: 'Парк' }], stairs: true, estimatedMinutes: 5 };
const path = [[37, 55], [37.001, 55], [37.002, 55.002]];
const request = (body: unknown) => new Request('http://localhost/api/map/features', { method: 'POST', headers: { 'Idempotency-Key': 'route-test' }, body: JSON.stringify(body) });
let writes: Record<string, unknown>[], filters: unknown[], owner: boolean;
beforeEach(() => { writes = []; filters = []; owner = true; const db = { from(table: string) { let write: Record<string, unknown> | null = null; const chain = { select() { return chain; }, eq(k: string, v: unknown) { filters.push([k, v]); return chain; }, insert(v: Record<string, unknown>) { write = v; writes.push(v); return chain; }, update(v: Record<string, unknown>) { write = v; writes.push(v); return chain; }, maybeSingle: async () => ({ data: owner ? { id: table === 'pets' ? 'pet' : 'route', owner_id: 'owner' } : null }), single: async () => ({ data: { id: 'route', ...write } }) }; return chain; } }; mocks.db.mockReturnValue(db); mocks.auth.mockResolvedValue({ user: { id: 'owner' }, supabase: db }); mocks.session.mockReturnValue(null); });
it('roundtrips stops separately from geometry through account create', async () => { const response = await POST(request({ type: 'route', petId: 'pet', title: 'Прогулка', path, planning: plan })); expect(response.status).toBe(201); expect(writes[0].planning).toEqual(plan); expect(filters).toContainEqual(['owner_id', 'owner']); const route = normalizeOwnerRoutes([(await response.json()).feature])[0]; expect(route.planning?.stops).toHaveLength(2); expect(route.path.coordinates).toHaveLength(3); });
it('rejects malformed planning without writing', async () => { expect((await POST(request({ type: 'route', petId: 'pet', title: 'Прогулка', path, planning: { ...plan, stops: [{ point: ['37', 55] }] } }))).status).toBe(400); expect(writes).toHaveLength(0); });
it('old clients save without invented stop metadata', async () => { const response = await POST(request({ type: 'route', petId: 'pet', title: 'Старый', path })); expect(response.status).toBe(201); expect(writes[0].planning).toBeNull(); });
it('updates owned geometry and named stops together while closing old share URL', async () => { const response = await PATCH(request({ path, planning: plan }), { params: Promise.resolve({ id: 'route' }) }); expect(response.status).toBe(200); expect(writes[0]).toMatchObject({ planning: plan, visibility: 'private', share_token: null }); expect(filters.filter(f => JSON.stringify(f) === '["owner_id","owner"]')).toHaveLength(2); });
it('cannot update another owner route', async () => { owner = false; expect((await PATCH(request({ path, planning: plan }), { params: Promise.resolve({ id: 'other' }) })).status).toBe(404); expect(writes).toHaveLength(0); });
it('metadata-only update preserves existing planning and GPS geometry', async () => { expect((await PATCH(request({ title: 'Новое имя' }), { params: Promise.resolve({ id: 'route' }) })).status).toBe(200); expect(writes[0]).not.toHaveProperty('planning'); expect(writes[0]).not.toHaveProperty('path'); });
