import {chromium,webkit} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:3238';
const out='docs/map-place-value/ux-prototype';await fs.mkdir(out,{recursive:true});
const pet={id:'route-test-pet',name:'Мята',owner_id:'route-test-owner'};
const profile={dogName:pet.name,backendPetId:pet.id,breedId:'mixed',breedGroupId:'mixed',lifeStage:'взрослая',size:'средняя',vaccineStatus:'актуально',parasiteStatus:'актуально',socialMode:'сначала спросить',energyLevel:'обычный',neighborhood:'Сокол',photos:[],selectedStyle:'city'};
const report=[];
for(const engine of (process.env.ENGINE?[process.env.ENGINE]:['chromium','webkit'])){
 const browser=await({chromium,webkit}[engine]).launch();
 try{for(const width of (process.env.WIDTH?[+process.env.WIDTH]:[320,390,1280])){
 let saved=[],failCalc=false,failSave=true,saves=0;const errors=[];
 const context=await browser.newContext({viewport:{width,height:width===1280?720:width===320?740:844},...(process.env.RECORD?{recordVideo:{dir:out+'/video',size:{width:390,height:844}}}:{}),geolocation:{latitude:55.744,longitude:37.603},permissions:['geolocation'],reducedMotion:'reduce'});
 await context.addInitScript(({profile})=>{Object.defineProperty(window,'Telegram',{configurable:false,value:{WebApp:{initData:'route-value-fixture',ready(){},expand(){},enableClosingConfirmation(){}}}});localStorage.setItem('pso.topapp.onboarding.v1','done');localStorage.setItem('pso.product.profile.v5',JSON.stringify(profile));},{profile});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://telegram.org/js/**',r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
 const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 await page.route('**/api/v1/session/telegram',r=>json(r,{mode:'telegram',session:{psyoUserId:pet.owner_id,ownerId:pet.owner_id,firstName:pet.name}}));
 await page.route('**/api/app/bootstrap**',r=>json(r,{mode:'owner',connected:true,pet,pets:[pet],profile,activePetId:pet.id,reminders:[],wishlist:[],zones:[],routes:saved,observations:[],documents:[]}));
 await page.route('**/api/map/features**',r=>{if(r.request().method()==='GET')return json(r,{features:[]});saves++;if(failSave){failSave=false;return json(r,{error:'TEST_STORAGE_FAILURE'},503);}const b=r.request().postDataJSON();const feature={id:'saved-route',title:b.title,description:b.description,pet_id:pet.id,route_source:b.routeSource,planning:b.planning,path:{type:'LineString',coordinates:b.path},path_gaps:b.pathGaps,visibility:b.visibility};saved=[feature];return json(r,{feature},201);});
 await page.route('**/api/map/walking',r=>{if(failCalc){failCalc=false;return json(r,{error:'NO_PATH'},422);}const {points}=r.request().postDataJSON();const path=[];for(let i=0;i<points.length;i++){if(i)path.push([(points[i-1][0]+points[i][0])/2,points[i][1]]);path.push(points[i]);}return json(r,{path,distanceMeters:920,estimatedMinutes:13,stairs:true,snaps:points.map(point=>({point,distanceMeters:0})),source:'OpenStreetMap'});});
 await page.route('**/api/map/search**',r=>json(r,{results:[{id:'osm:node:test',kind:'organization',title:'Тестовый парк',category:'park',detail:'Тестовые данные',point:{lat:55.745,lng:37.604}}]}));
 const places=[{id:'p1',title:'Сад у набережной',point:{lat:55.735,lng:37.595}},{id:'p2',title:'Площадка у пруда',point:{lat:55.74,lng:37.61}},{id:'p3',title:'Тихий сквер',point:{lat:55.748,lng:37.62}}].map(p=>({...p,category:'парк',detail:'Пример для проверки сценария',source:{provider:'pso',id:p.id},note:''}));
 const library={version:1,collections:[{id:'saved',title:'Все сохранённые',placeIds:['p1','p2','p3']},{id:'evening',title:'Вечерняя прогулка',placeIds:['p1','p2']},{id:'weekend',title:'На выходные',placeIds:['p2','p3']}],places,appliedCommands:[]};
 await page.route('**/api/map/library**',r=>json(r,{library}));
 await page.route('**/api/map/places?**',r=>json(r,{error:'AREA_NOT_COVERED'},422));
 await page.route('**/api/social/**',r=>json(r,{signals:[],requests:[],profile:null,candidates:[],viewer:{approximateLocation:{lat:55.744,lng:37.603},radiusMeters:3000}}));

 await page.goto(base,{waitUntil:'domcontentloaded'});
 await page.locator('.app-tabs button[data-route="map"]').click();
 await page.locator('.leaflet-container').waitFor();
 await page.getByRole('button',{name:'Сохранённое',exact:true}).click();
 const collectionSelect=page.getByRole('combobox',{name:'Открыть подборку',exact:true});
 await collectionSelect.selectOption('evening');
 await page.waitForTimeout(800);
 assert.equal(await page.locator('.map-library-places li').count(),2);
 assert.equal(await page.locator('.pso-map-marker[title^="Тихий сквер"]').count(),0);
 assert.equal(await page.locator('.pso-map-marker[title^="Сад у набережной"]').count(),1);
 await collectionSelect.selectOption('weekend');await page.waitForTimeout(800);
 assert.equal(await page.locator('.pso-map-marker[title^="Сад у набережной"]').count(),0);
 assert.equal(await page.locator('.pso-map-marker[title^="Тихий сквер"]').count(),1);
 await collectionSelect.selectOption('evening');await page.waitForTimeout(800);
 async function shot(name){
  await page.locator('.production-map-workspace').evaluate(el=>el.scrollTop=0);
  await page.locator('.map-work-area').evaluate(el=>el.scrollTop=0);
  await page.locator('.map-surface-overlay').waitFor({state:'hidden',timeout:60000});await page.waitForTimeout(1200);
  await page.screenshot({path:`${out}/${name}-${engine}-${width}.png`});
 }
 await shot('01-collection');
 // Marker and list open the same place; Back restores the collection, not a new search.
 await page.locator('.pso-map-marker[title^="Сад у набережной"]').click();
 await page.locator('.map-place-panel').waitFor();assert.match(await page.locator('.map-place-panel').innerText(),/Сад у набережной/);
 await page.getByRole('button',{name:'К подборке',exact:true}).click();
 const first=page.locator('.map-library-places li').first();
 await first.getByRole('button',{name:'Сад у набережной Пример для проверки сценария',exact:true}).click();
 await page.getByRole('button',{name:'К подборке',exact:true}).click();
 await page.waitForFunction(el=>document.activeElement===el,await first.getByRole('button',{name:'Сад у набережной Пример для проверки сценария',exact:true}).elementHandle());
 await first.getByRole('button',{name:'В прогулку',exact:true}).click();
 await page.locator('.map-resume-draft').filter({hasText:'1 точка'}).waitFor();
 assert.equal(await first.getByRole('button',{name:'В прогулке',exact:true}).isDisabled(),true);
 await page.locator('.map-library-places li').nth(1).locator('input[type="checkbox"]').check();
 await page.getByRole('button',{name:'Добавить в прогулку · 1',exact:true}).click();
 await page.locator('.map-resume-draft').filter({hasText:'2 точки'}).waitFor();
 assert.equal(await page.locator('.pso-route-stop-marker').count(),2);
 await shot('02-plan-and-collection');
 // A genuinely arbitrary map point joins the same draft.
 await page.locator('.leaflet-container').click({position:{x:100,y:70}});
 await page.getByRole('button',{name:'Добавить в маршрут',exact:true}).click();
 await page.getByRole('button',{name:'Добавить остановку',exact:true}).click();
 assert.equal(await page.locator('.map-waypoint-list li').count(),3);
 await page.getByRole('button',{name:'Точка 2: выше',exact:true}).click();
 assert.match(await page.locator('.map-waypoint-list li').first().innerText(),/Площадка у пруда/);
 await shot('03-editor');
 await page.getByRole('button',{name:'Свернуть маршрут',exact:true}).click();
 assert.equal(await collectionSelect.inputValue(),'evening');
 await page.getByRole('button',{name:'Продолжить',exact:true}).click();
 assert.equal(await page.locator('.map-waypoint-list li').count(),3);
 failCalc=true;await page.getByRole('button',{name:'Рассчитать пеший путь',exact:true}).click();
 await page.locator('.route-calculation-error').waitFor();
 assert.equal(await page.getByRole('button',{name:'Готово',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Рассчитать пеший путь',exact:true}).click();
 await page.getByRole('button',{name:'Применить этот путь',exact:true}).click();
 await page.getByRole('button',{name:'Готово',exact:true}).click();
 await page.getByRole('button',{name:'Сохранить лично',exact:true}).click();await page.waitForTimeout(300);
 assert.equal(saved.length,0);assert.equal(await page.locator('[data-route-flow="plan-review"]').count(),1);
 await page.getByRole('button',{name:'Сохранить лично',exact:true}).click();
 await page.locator('.production-map-saved-row.route').waitFor();
 assert.equal(saved.length,1);assert.equal(saved[0].planning.stops.length,3);assert.equal(saves,2);
 assert.deepEqual(saved[0].planning.stops.slice(0,2).map(p=>p.placeId),['p2','p1']);
 const snapshot=JSON.stringify(saved[0]);
 await page.reload({waitUntil:'domcontentloaded'});
 await page.locator('.app-tabs button[data-route="map"]').click();
 await page.getByRole('button',{name:'Сохранённое',exact:true}).click();
 await page.locator('.production-map-saved-row.route').getByRole('button',{name:'Открыть',exact:true}).click();
 await page.locator('[data-route-flow="plan-review"]').waitFor();
 assert.equal(JSON.stringify(saved[0]),snapshot);
 await shot('04-reopened');
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Скачать GPX',exact:true}).click()]);
 await download.saveAs(`${out}/walk-${engine}-${width}.gpx`);
 await page.getByRole('button',{name:'Изменить остановки',exact:true}).click();
 assert.equal(await page.locator('.map-waypoint-list li').count(),3);
 await page.getByRole('button',{name:'Удалить точку 2',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Готово',exact:true}).isDisabled(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 report.push({engine,width,collectionMapSync:true,mapListSelection:true,focusReturn:true,appendToNonemptyPlan:true,duplicatePlacePrevented:true,mapPointSamePlan:true,backContext:true,calculationFailure:true,saveFailure:true,reopen:true,gpx:true,staleGuard:true,fixture:true});console.log(engine,width,'PASS');
 await context.close();
 }}finally{await browser.close();}
}
await fs.writeFile(`${out}/verification.json`,JSON.stringify(report,null,2));
