import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {setup,fs}=require('../../docs/unified-release-20260909/evidence/harness.cjs');
const out=process.env.OUT_DIR||'artifacts/unified-care';
await fs.mkdir(out,{recursive:true});
const results=[];
for(const [engine,width] of [['chromium',390],['webkit',320],['chromium',1100]]){
 const t=await setup(engine,width),{page,ctx,state,pet}=t;
 let failCheckin=true,failCare=false,failRead=false;
 const keys=[];
 const habits=[{id:'22222222-2222-4222-8222-222222222222',petId:pet.id,title:'Вечернее кормление',kind:'feeding',cadence:'daily',targetPerPeriod:1,status:'active',checkins:[]}];
 try{
  await ctx.route('**/api/reminders?*',route=>route.fulfill({status:failCare?503:200,json:failCare?{error:'QA_FAILURE'}:{reminders:[],mode:'user'}}));
  await ctx.route('**/api/habits?*',route=>route.fulfill({status:failRead?503:200,json:failRead?{error:'QA_FAILURE'}:{habits}}));
  await ctx.route('**/api/habits/*/checkins',async route=>{
   keys.push(route.request().headers()['idempotency-key']);
   if(failCheckin)return route.fulfill({status:503,json:{error:'QA_FAILURE'}});
   habits[0].checkins.push({id:'checkin-1',completedAt:new Date().toISOString()});
   return route.fulfill({json:{ok:true}});
  });
  await ctx.route('**/api/observations',async route=>{
   if(route.request().method()!=='POST')return route.fallback();
   const body=route.request().postDataJSON();
   const row={id:'33333333-3333-4333-8333-333333333333',petId:pet.id,createdAt:body.observedAt,observedAt:body.observedAt,note:body.note,type:body.type||'note',value:body.value,mood:body.mood,appetite:body.appetite,stool:body.stool,energy:body.energy};
   state.observations.unshift(row);
   return route.fulfill({json:{observation:row,mode:'supabase'}});
  });
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('.app-tabs').waitFor();
  const care=async()=>{await t.nav('all');assert.equal(await page.locator('[data-tool-destination=health],[data-tool-destination=habits]').count(),0);await page.locator('[data-tool-destination=calendar]').click();await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();await page.getByRole('button',{name:'Календарь',exact:true}).waitFor();};
  const back=()=>page.getByRole('button',{name:'Назад',exact:true}).first().click();
  await care();
  await page.getByRole('button',{name:'Отметить: Вечернее кормление',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Не получилось отметить дело'}).waitFor();
  assert.equal(habits[0].checkins.length,0);
  await page.getByRole('button',{name:'Все регулярные дела',exact:true}).click();
  await page.getByRole('heading',{name:/Регулярные дела/}).waitFor();
  await page.getByRole('alert').filter({hasText:'Не получилось отметить дело'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Отметить',exact:true}).isEnabled(),true);
  await back();
  failCheckin=false;await page.getByRole('button',{name:'Отметить: Вечернее кормление',exact:true}).click();
  await page.getByRole('button',{name:'Выполнено: Вечернее кормление',exact:true}).waitFor();
  assert.equal(keys.length,2);assert.ok(keys[0]);assert.equal(keys[0],keys[1]);assert.equal(habits[0].checkins.length,1);
  await page.getByRole('button',{name:'Все регулярные дела',exact:true}).click();
  await page.getByRole('heading',{name:/Регулярные дела/}).waitFor();await back();await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();
  await page.getByRole('button',{name:'Добавить наблюдение',exact:true}).click();
  await page.locator('#observe-text').fill('После прогулки спокойно отдыхает');
  await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();
  await page.getByText('Запись сохранена',{exact:true}).waitFor();
  await page.getByRole('button',{name:'В календарь',exact:true}).click();await page.getByRole('button',{name:'Обзор',exact:true}).click();
  await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();
  await page.locator('.cw-observation').filter({hasText:'После прогулки спокойно отдыхает'}).waitFor();
  await page.getByRole('button',{name:'История наблюдений',exact:true}).click();
  await page.getByRole('button').filter({hasText:'Контрольная запись для открытия'}).click();
  await page.locator('.note-body').filter({hasText:'Контрольная запись для открытия'}).waitFor();await back();await page.getByRole('button',{name:'Обзор',exact:true}).click();
  await page.locator('[data-domain=food]').click();await page.getByRole('heading',{name:'Питание',exact:true}).waitFor();
  await page.getByRole('button',{name:'Выполнено: Вечернее кормление',exact:true}).waitFor();
  await page.getByRole('button',{name:'Все регулярные дела',exact:true}).click();await page.getByRole('heading',{name:/Регулярные дела/}).waitFor();await back();
  await page.getByRole('heading',{name:'Питание',exact:true}).waitFor();await back();
  await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();
  await page.locator('.cw-observation').filter({hasText:'После прогулки спокойно отдыхает'}).waitFor();
  await page.getByRole('button',{name:'Выполнено: Вечернее кормление',exact:true}).waitFor();
  await page.evaluate(()=>document.fonts.ready);await page.locator('#pso-exact-content').evaluate(el=>el.scrollTop=0);await page.addStyleTag({content:'nextjs-portal{display:none!important}'});await page.screenshot({path:`${out}/${engine}-${width}-overview.png`});
  assert.ok(await page.locator('#pso-exact-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'no horizontal overflow');
  await t.nav('profile');assert.equal(await page.locator('.list button').filter({hasText:/^(Наблюдения|Привычки)/}).count(),0);
  await page.getByRole('button').filter({hasText:'Дела, наблюдения и привычки'}).click();await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();
  await t.nav('today');await page.getByRole('button').filter({hasText:'Забота о Мяте'}).click();await page.getByRole('heading',{name:'Забота',exact:true}).waitFor();
  failCare=true;await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('alert').filter({hasText:'Не удалось загрузить дела'}).waitFor();
  await page.getByRole('button',{name:'Добавить наблюдение',exact:true}).waitFor();
  await page.getByRole('button',{name:'Выполнено: Вечернее кормление',exact:true}).waitFor();
  failCare=false;failRead=true;await page.reload({waitUntil:'domcontentloaded'});
  await page.getByRole('region',{name:'Регулярные дела в заботе'}).getByRole('alert').waitFor();
  failRead=false;await page.getByRole('region',{name:'Регулярные дела в заботе'}).getByRole('button',{name:'Повторить'}).click();
  await page.getByRole('button',{name:'Выполнено: Вечернее кормление',exact:true}).waitFor();
  assert.deepEqual(t.errors,[]);
  results.push({engine,width,pass:true,scope:'mock API: unified entries, observation create + old history + reload, habit checkin failure/retry same key + reload, domain placement, back, independent load errors'});
 }finally{await t.browser.close();}
}
await fs.writeFile(`${out}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));
