import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const b=await chromium.launch();
try {for(const width of [320,390]){
 const p=await b.newPage({viewport:{width,height:844}});await p.route('https://telegram.org/**',r=>r.abort());p.setDefaultTimeout(10000);await p.route('**/api/app/bootstrap*',r=>r.fulfill({json:{mode:'demo',connected:false,empty:true,pets:[]}}));await p.addInitScript(()=>{window.Telegram={WebApp:{initData:'',ready(){},expand(){},enableClosingConfirmation(){}}};if(sessionStorage.getItem('forms-seeded'))return;sessionStorage.setItem('forms-seeded','1');localStorage.setItem('pso.topapp.onboarding.v1','done');localStorage.setItem('pso.product.profile.v5',JSON.stringify({dogName:'Мята',breedId:'mixed',lifeStage:'взрослая',photos:[],backendPetId:'guest-forms-review'}));});await p.goto('http://localhost:3214/',{waitUntil:'networkidle'});
 await p.locator('.app-tabs [data-route="things"]').click();await p.getByRole('button',{name:'Добавить в список',exact:true}).click();
 await p.locator('.thing-capture').getByLabel('Название',{exact:true}).fill('Тестовый поводок');await p.locator('.thing-plan-option input').uncheck();await p.getByRole('button',{name:'Добавить в вещи',exact:true}).click();
 let row=p.locator('.wishlist-item').filter({hasText:'Тестовый поводок'});await row.getByRole('button',{name:'Изменить',exact:true}).click();await p.locator('.wishlist-edit-form').getByLabel('Название',{exact:true}).fill('Поводок для прогулок');await p.locator('.wishlist-edit-form').getByRole('button',{name:'Сохранить',exact:true}).click();
 row=p.locator('.wishlist-item').filter({hasText:'Поводок для прогулок'});await row.getByRole('button',{name:'Куплено',exact:true}).click();await row.getByRole('button',{name:'Вернуть',exact:true}).waitFor();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('pso.product.entities.v1:guest-forms-review')||'{}').wishlist?.some(x=>x.title==='Поводок для прогулок'&&x.status==='bought'));
 await p.reload({waitUntil:'networkidle'});await p.locator('.app-tabs [data-route="things"]').click();await p.getByRole('button',{name:'Добавить в список',exact:true}).click();
 row=p.locator('.wishlist-item').filter({hasText:'Поводок для прогулок'});await row.getByRole('button',{name:'Вернуть',exact:true}).click();await row.getByRole('button',{name:'Куплено',exact:true}).waitFor();
 await p.locator('.app-tabs [data-route="today"]').click();await p.getByRole('button',{name:'Открыть план ухода',exact:true}).first().click();
 const c=p.locator('.care-composer');await c.getByPlaceholder('Например: обработка от клещей').fill('Тестовое дело ухода');await c.getByRole('button',{name:'Добавить дело',exact:true}).click();
 const care=p.locator('.care-task-card').filter({hasText:'Тестовое дело ухода'});await care.getByRole('button',{name:'Готово',exact:true}).click();await p.getByRole('button',{name:'История',exact:true}).click();await p.locator('.care-task-card.done').filter({hasText:'Тестовое дело ухода'}).waitFor();
 await p.waitForFunction(()=>JSON.parse(localStorage.getItem('pso.product.entities.v1:guest-forms-review')||'{}').reminders?.some(x=>x.title==='Тестовое дело ухода'&&x.status==='done'));await p.reload({waitUntil:'networkidle'});await p.locator('.app-tabs [data-route="today"]').click();await p.locator('.journal-entry').filter({hasText:'Тестовое дело ухода'}).waitFor();assert.ok(await p.locator('.journal-entry').filter({hasText:'Тестовое дело ухода'}).count(),'completed care record retained in daily journal');
 console.log(`PASS ${width}: wishlist create/edit/complete/reload/restore; care create/complete/reload into journal; guest local data only`);await p.close();
}} finally {await b.close()}
